baseURL = 'https://xihutaijixiongv2.github.io/'
title = '我的个人博客'
theme = 'hugo-theme-stack'

languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'

[pagination]
  pagerSize = 10

[languages.zh-cn]
  title = "我的个人博客"
  weight = 1

[params]
  subtitle = "从 Obsidian 自动发布的博客"
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3

# 移除 JSON 输出
[outputs]
  home = ["HTML", "RSS"]
