name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Theme
        run: |
          echo "=== 验证主题文件 ==="
          ls -la themes/hugo-theme-stack/
          echo "主题布局文件: $(find themes/hugo-theme-stack/layouts -name '*.html' | wc -l) 个"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Site
        run: |
          echo "=== 构建网站 ==="
          hugo --minify
          echo "=== 构建结果 ==="
          echo "总文件数: $(find public -type f | wc -l)"
          echo "HTML文件: $(find public -name '*.html' | wc -l) 个"
          echo "CSS/JS文件: $(find public -name '*.css' -o -name '*.js' | wc -l) 个"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
